service: confoo-service-demo # (1)

provider:
  name: aws
  deploymentMethod: direct
  runtime: provided.al2 # (2)
  region: ${env:AWS_REGION} # (3)

package: #(4)
  artifact: target/lambda/confoo/bootstrap.zip

functions: # (5)
  hello-world: 
    handler: bootstrap # (6)
    environment: # (7)
      TABLE_NAME: confoo-pizza-demo
    events: # (8)
      - http:
          path: /pizza/{pizza_name}
          method: get
          request:
            parameters:
              paths:
                pizza_name: true
      - http:
          path: /pizza
          method: post

resources: # (9)
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: confoo-pizza-demo
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1