service: pizza-service-demo # (1)

provider:
  name: aws
  deploymentMethod: direct
  runtime: provided.al2023 # (2)
  region: ${env:AWS_REGION} # (3)
  iamRoleStatements:
  - Effect: Allow
    Action: "dynamodb:PutItem"
    Resource: "arn:aws:dynamodb:${env:AWS_REGION}:${aws:accountId}:table/pizza-service-demo"
  - Effect: Allow
    Action: "dynamodb:Query"
    Resource: "arn:aws:dynamodb:${env:AWS_REGION}:${aws:accountId}:table/pizza-service-demo"

package: #(4)
  artifact: target/lambda/pizza-service-demo/bootstrap.zip

functions: # (5)
  pizza:
    handler: bootstrap # (6)
    environment: # (7)
      TABLE_NAME: pizza-service-demo
    events: # (8)
      - http:
          path: /pizza/{pizza_name}
          method: get
          request:
            parameters:
              paths:
                pizza_name: true
      - http:
          path: /pizza
          method: post

resources: # (9)
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pizza-service-demo
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1