service: confoo-service-demo # (1)

provider:
  name: aws
  deploymentMethod: direct
  runtime: provided.al2 # (2)
  region: us-east-1 # (3)
  iamRoleStatements:
    - Effect: Allow
      Action: "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/confoo-pizza-demo"
    - Effect: Allow
      Action: "dynamodb:Query"
      Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/confoo-pizza-demo"

package: #(4)
  artifact: target/lambda/confoo/bootstrap.zip

functions: # (5)
  hello-world: 
    handler: bootstrap # (6)
    environment:
      TABLE_NAME: confoo-pizza-demo
    events: # (7)
      - http:
          path: /pizza/{pizza_name}
          method: get
          request:
            parameters:
              paths:
                pizza_name: true
      - http:
          path: /pizza
          method: post

resources: 
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: confoo-pizza-demo
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1