service: confoo-service # (1)

provider:
  name: aws
  deploymentMethod: direct
  runtime: provided.al2 # (2)
  region: us-east-1 # (3)
  iamRoleStatements:
    - Effect: Allow
      Action: "dynamodb:GetItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/confoo-pizza"

package: #(4)
  artifact: target/lambda/confoo/bootstrap.zip

functions: # (5)
  hello-world: 
    handler: bootstrap # (6)
    environment:
      TABLE_NAME: confoo-pizza
    events: # (7)
      - http:
          path: /pizza
          method: get