name: Test

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test