name: Test

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test and package
        run: ./build.sh

      - name: Deploy
        run: |
          serverless deploy
          URL=$(serverless info --verbose 2>/dev/null | grep ServiceEndpoint | sed s/ServiceEndpoint\:\ //g | awk '{print $1}')
          echo "URL=$URL" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Run integration tests 
        run: cargo test --test '*' -- --nocapture
        env:
          URL: ${{ env.URL }}

      - name: Destroy
        run: serverless remove
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1